"""
System Configuration & Constants (PRJ-07).
Defines the configurable identifier hierarchy, canonical schema definitions,
synonym dictionaries for deterministic schema mapping, and job lifecycle statuses.
"""

from typing import Dict, List, Any

# ==============================================================================
# 1. STANDARDIZED JOB STATUSES (Strict 6-State Lifecycle Model)
# ==============================================================================
JOB_STATUS_QUEUED = "QUEUED"
JOB_STATUS_RUNNING = "RUNNING"
JOB_STATUS_PAUSED_RECOVERABLE = "PAUSED_RECOVERABLE"
JOB_STATUS_COMPLETED = "COMPLETED"
JOB_STATUS_FAILED = "FAILED"
JOB_STATUS_FAILED_INTERRUPTED = "FAILED_INTERRUPTED"

VALID_JOB_STATUSES = {
    JOB_STATUS_QUEUED,
    JOB_STATUS_RUNNING,
    JOB_STATUS_PAUSED_RECOVERABLE,
    JOB_STATUS_COMPLETED,
    JOB_STATUS_FAILED,
    JOB_STATUS_FAILED_INTERRUPTED,
}

# ==============================================================================
# 2. CANONICAL TARGET FIELDS
# ==============================================================================
CANONICAL_FIELDS: Dict[str, Dict[str, Any]] = {
    "email": {
        "label": "Email Address",
        "type": "email",
        "is_identifier": True,
        "description": "Normalized electronic mail address",
    },
    "phone": {
        "label": "Phone Number",
        "type": "phone",
        "is_identifier": True,
        "description": "Normalized 10-digit / E.164 contact number",
    },
    "aadhaar": {
        "label": "Aadhaar / National ID",
        "type": "aadhaar",
        "is_identifier": True,
        "description": "Normalized 12-digit Aadhaar / National Identity Number",
    },
    "username": {
        "label": "Username / Handle",
        "type": "text",
        "is_identifier": True,
        "description": "Unique online handle or user identifier",
    },
    "member_id": {
        "label": "Member / Employee ID",
        "type": "text",
        "is_identifier": True,
        "description": "Enterprise customer, employee, or member ID",
    },
    "name": {
        "label": "Full Name / Title",
        "type": "name",
        "is_identifier": False,
        "description": "Person full name or entity title",
    },
    "first_name": {
        "label": "First Name",
        "type": "name",
        "is_identifier": False,
        "description": "Given first name",
    },
    "last_name": {
        "label": "Last Name",
        "type": "name",
        "is_identifier": False,
        "description": "Surname / family last name",
    },
    "business_name": {
        "label": "Business / Place Name",
        "type": "name",
        "is_identifier": False,
        "description": "Commercial store, venue, or business establishment name",
    },
    "company": {
        "label": "Company / Organization",
        "type": "text",
        "is_identifier": False,
        "description": "Company, employer, or business organization",
    },
    "address": {
        "label": "Street Address / Location",
        "type": "address",
        "is_identifier": False,
        "description": "Physical address, street, or city/location",
    },
    "city": {
        "label": "City / Locality",
        "type": "text",
        "is_identifier": False,
        "description": "City, town, or municipal locality",
    },
    "rating": {
        "label": "Rating / Score",
        "type": "numeric",
        "is_identifier": False,
        "description": "Customer rating, review score, or satisfaction index",
    },
    "category": {
        "label": "Category / Industry",
        "type": "text",
        "is_identifier": False,
        "description": "Business category, classification, or industry sector",
    },
    "review_count": {
        "label": "Review Count",
        "type": "numeric",
        "is_identifier": False,
        "description": "Total volume of customer reviews or ratings",
    },
    "latitude": {
        "label": "Latitude",
        "type": "numeric",
        "is_identifier": False,
        "description": "Geographic latitude coordinate",
    },
    "longitude": {
        "label": "Longitude",
        "type": "numeric",
        "is_identifier": False,
        "description": "Geographic longitude coordinate",
    },
    "role": {
        "label": "Role / Designation",
        "type": "text",
        "is_identifier": False,
        "description": "Job title or role in organization",
    },
    "notes": {
        "label": "Additional Notes / Skills",
        "type": "text",
        "is_identifier": False,
        "description": "Unstructured descriptive metadata",
    },
}

# ==============================================================================
# 3. DETERMINISTIC SYNONYM DICTIONARY FOR SCHEMA MAPPING
# ==============================================================================
CANONICAL_SYNONYMS: Dict[str, List[str]] = {
    "email": [
        "email",
        "email_id",
        "email_address",
        "e_mail",
        "mail",
        "user_email",
        "contact_email",
        "electronic_mail",
        "primary_email",
    ],
    "phone": [
        "phone",
        "mobile",
        "mobile_no",
        "mobile_number",
        "contact",
        "contact_no",
        "contact_number",
        "contact_phone",
        "phone_no",
        "phone_number",
        "cell",
        "telephone",
        "cell_no",
        "primary_phone",
    ],
    "aadhaar": [
        "aadhaar",
        "aadhar",
        "aadhaar_number",
        "aadhar_number",
        "aadhaar_no",
        "aadhar_no",
        "aadhaar_card",
        "aadhar_card",
        "uid",
        "uid_number",
        "national_id",
    ],
    "first_name": [
        "first_name",
        "fname",
        "given_name",
        "first",
    ],
    "last_name": [
        "last_name",
        "lname",
        "surname",
        "last",
        "family_name",
    ],
    "name": [
        "full_name",
        "name",
        "person_name",
        "employee_name",
        "customer_name",
        "member_name",
        "user_name",
        "display_name",
        "contact_name",
        "title",
        "business_name",
        "store_name",
        "place_name",
        "venue_name",
    ],
    "business_name": [
        "business_name",
        "store_name",
        "shop_name",
        "place_name",
        "venue_name",
        "outlet_name",
        "establishment",
        "brand_name",
        "establishment_name",
    ],
    "username": [
        "username",
        "user_name",
        "user_id",
        "user_handle",
        "handle",
        "screen_name",
        "nick",
        "nickname",
        "login",
        "account_id",
    ],
    "member_id": [
        "member_id",
        "employee_id",
        "emp_id",
        "cust_id",
        "customer_id",
        "client_id",
        "emp_code",
        "staff_id",
        "uid",
    ],
    "address": [
        "address",
        "residential_address",
        "residence_address",
        "street_address",
        "addr",
        "address_1",
        "address_2",
        "residence",
        "street",
        "location",
        "state",
        "postal_address",
        "full_address",
        "formatted_address",
        "home_address",
    ],
    "city": [
        "city",
        "city_name",
        "town",
        "town_name",
        "locality",
        "municipality",
        "district",
        "suburb",
    ],
    "company": [
        "company",
        "company_name",
        "organization",
        "org_name",
        "employer",
        "firm",
        "corp",
        "workplace",
        "department",
        "brand",
    ],
    "rating": [
        "rating",
        "ratings",
        "stars",
        "star_rating",
        "score",
        "avg_rating",
        "average_rating",
        "user_rating",
        "rating_score",
    ],
    "category": [
        "category",
        "categories",
        "business_category",
        "industry",
        "sector",
        "type",
        "business_type",
        "genre",
        "sub_category",
        "main_category",
    ],
    "review_count": [
        "review_count",
        "reviews",
        "num_reviews",
        "total_reviews",
        "review_num",
        "ratings_count",
        "user_ratings_total",
        "count_of_reviews",
    ],
    "latitude": [
        "latitude",
        "lat",
        "lat_coord",
        "geo_latitude",
        "y_coord",
    ],
    "longitude": [
        "longitude",
        "lng",
        "lon",
        "long",
        "geo_longitude",
        "x_coord",
    ],
    "role": [
        "role",
        "designation",
        "job_title",
        "title_role",
        "position",
        "profession",
        "occupation",
    ],
    "department": [
        "department",
        "dept",
        "division",
        "team",
        "unit",
        "business_unit",
    ],
    "salary": [
        "salary",
        "compensation",
        "pay",
        "wage",
        "ctc",
        "annual_salary",
    ],
    "bio": [
        "bio",
        "bio_text",
        "biography",
        "user_bio",
        "profile_bio",
        "about",
        "about_me",
        "description",
        "profile_description",
    ],
    "followers": [
        "followers",
        "followers_count",
        "follower_count",
        "subscribers",
        "subscriber_count",
        "audience_count",
    ],
    "following": [
        "following",
        "following_count",
        "follows_count",
        "friends_count",
    ],
    "platform": [
        "platform",
        "social_platform",
        "network",
        "social_network",
        "source_app",
        "channel",
    ],
    "notes": [
        "skills",
        "notes",
        "metadata",
        "remarks",
        "details",
        "join_date",
        "website",
        "url",
    ],
}

# ==============================================================================
# 4. CONFIGURABLE IDENTIFIER MATCHING HIERARCHY
# (Descriptive fields like rating, category, coordinates are NEVER placed here)
# ==============================================================================
IDENTIFIER_HIERARCHY: List[Dict[str, Any]] = [
    {
        "identifier_type": "email",
        "canonical_field": "email",
        "priority": 1,
        "match_type": "exact",
        "confidence": 1.0,
        "description": "Exact match on normalized lowercase email address",
    },
    {
        "identifier_type": "phone",
        "canonical_field": "phone",
        "priority": 2,
        "match_type": "exact",
        "confidence": 0.98,
        "description": "Exact match on normalized 10-digit / E.164 phone number",
    },
    {
        "identifier_type": "aadhaar",
        "canonical_field": "aadhaar",
        "priority": 3,
        "match_type": "exact",
        "confidence": 1.0,
        "description": "Exact match on normalized 12-digit Aadhaar / National ID",
    },
    {
        "identifier_type": "username",
        "canonical_field": "username",
        "priority": 4,
        "match_type": "exact",
        "confidence": 0.95,
        "description": "Exact match on alphanumeric username handle",
    },
    {
        "identifier_type": "member_id",
        "canonical_field": "member_id",
        "priority": 5,
        "match_type": "exact",
        "confidence": 0.95,
        "description": "Exact match on enterprise member / employee code",
    },
    {
        "identifier_type": "name_address_fuzzy",
        "canonical_fields": ["name", "address"],
        "priority": 6,
        "match_type": "composite_fuzzy",
        "confidence_threshold": 0.88,
        "description": "High-confidence composite fuzzy similarity (Jaro-Winkler + Levenshtein)",
    },
]

# Database Path
DEFAULT_DB_PATH = "data/unified_repository.duckdb"
DEMO_DATA_DIR = "data/demo"
